import {
  AbonementType, 
  IAbonementConsumable, 
  IAbonementOffer, 
  ILesson, 
  IRule, 
  ISubject, 
  ITeacher, 
  IUser, 
  LessonStatus, 
  PeriodicityType 
} from "../types/domain";
import { ISubjectView } from "../types/teacherDomainView";
import { IOption } from "./DropDownMenu";

export const oneDay = 1000*60*60*24;
export const oneHour = 1000*60*60;

export const textS = 'Lorem ipsum dolor sit amet cons'
export const textM = 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Autem eaque ducimus culpa nobis totam temporibus aspernatur repellendus dignissimos, excepturi, cum quo maiores voluptates vero vel.';
export const textL = 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam sint quos culpa nemo, tenetur, ratione quae a nisi, iusto adipisci veritatis odio provident magnam. Quidem at dolorum, perspiciatis odio beatae odit incidunt. Nisi corporis rem omnis? Ducimus obcaecati iste eos quas architecto, necessitatibus odit, minus aut consectetur veritatis ipsa vitae!';

export const mochDate2023_7_14_15_30_0 = new Date(2023, 7, 14, 15, 30, 0);

export const dummyRules: IRule[] = [
  {
    id: "111",
    durationMin: 60,
    periodicity: {
      periodicityType: PeriodicityType.weekly,
      periodicityRule: [1, 3],
    },
    timeStart: new Date(Date.now() + oneHour * 2),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "222",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.weekly,
      periodicityRule: [2, 4],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "333",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.weekly,
      periodicityRule: [1],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "444",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.weekly,
      periodicityRule: [1, 2, 3, 4, 5, 6, 7],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "555",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.manualDate,
      periodicityRule: [1604898452084],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "666",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.manualDate,
      periodicityRule: [],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
  {
    id: "777",
    durationMin: 120,
    periodicity: {
      periodicityType: PeriodicityType.weekly,
      periodicityRule: [],
    },
    timeStart: new Date(),
    teacherId: '',
    subjectId: '',
  },
];

export const dummyAbonementOffers:IAbonementOffer[] = [
  {
    id:'101',
    limitLessons: 0,
    limitTime: 0,
    price: 0,
    type: AbonementType.limited,
    subjects:[],
    teacherId: '',
  },
  {
    id:'202',
    limitLessons: 2,
    limitTime: 22,
    price: 222,
    type: AbonementType.limited,
    subjects:['2'],
    teacherId: '',
  },
  {
    id:'303',
    limitLessons: 3,
    limitTime: 30,
    price: 333,
    type: AbonementType.limited,
    subjects:['1', '2', '3', '4', '5',  '6', '7', '8', '9', '10'],
    teacherId: '',
  },
  {
    id:'404',
    limitLessons: 0,
    limitTime: 0,
    price: 0,
    type: AbonementType.unlimited,
    subjects:[],
    teacherId: '',
  },
  {
    id:'505',
    limitLessons: 2,
    limitTime: 22,
    price: 222,
    type: AbonementType.unlimited,
    subjects:['2'],
    teacherId: '',
  },
  {
    id:'606',
    limitLessons: 3,
    limitTime: 30,
    price: 333,
    type: AbonementType.unlimited,
    subjects:['1', '2', '3', '4', '5',  '6', '7', '8', '9', '10'],
    teacherId: '',
  },

]

export const dummySubjectViews: ISubjectView[] = [
  {
    id: '3',
    description: textL,
    name: 'Tratava Yuoga',
    rules: [dummyRules[0]],
    teacherId: '',
  },
  {
    id: '4',
    description: 'good yuoga',
    name: 'Tvarata Yuoga',
    rules: [dummyRules[1]],
    teacherId: '',
  },
  {
    id: '5',
    description: 'good yuoga',
    name: 'Empty Manual Date Yuoga',
    rules: [dummyRules[5]],
    teacherId: '',
  },
  {
    id: '6',
    description: 'good yuoga',
    name: 'Manual Day Yuoga',
    rules: [dummyRules[4]],
    teacherId: '',
  },
  {
    id: '7',
    description: textL,
    name: 'Every Day Yuoga',
    rules: [dummyRules[3]],
    teacherId: '',
  },
  {
    id: '8',
    description: 'good yuoga',
    name: 'One day Yuoga',
    rules: [dummyRules[2]],
    teacherId: '',
  },
  {
    id: '9',
    description: 'good yuoga',
    name: 'Empty Day Weekly Yuoga',
    rules: [dummyRules[6]],
    teacherId: '',
  },
];

export const dummySubjects: ISubject[] = [
  {
    id: '1',
    description: 'test very well yuoga test',
    name: 'Tratatata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '2',
    description: 'good yuoga',
    name: 'test Trata Yuoga test',
    rules: [],
    teacherId: '',
  },
  {
    id: '3',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '4',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '5',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '6',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '7',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '8',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '9',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '10',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '11',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
  {
    id: '12',
    description: 'good yuoga',
    name: 'Trata Yuoga',
    rules: [],
    teacherId: '',
  },
];

export const sampleAbonementOffers: IAbonementOffer[] = [
  {
    id: '1',
    teacherId: '1',
    subjects: ['1', '2', '4'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 1,
    price: 100,
  },
  {
    id: '2',
    teacherId: '1',
    subjects: ['1'],
    type:  AbonementType.limited,
    limitTime: 60,
    limitLessons: 10,
    price: 180,
  },
  {
    id: '3',
    teacherId: '1',
    subjects: ['1', '2', '3'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 5,
    price: 150,
  },
  {
    id: '4',
    teacherId: '1',
    subjects: [],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 5,
    price: 80,
  },
  {
    id: '5',
    teacherId: '1',
    subjects: ['1'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 50,
    price: 400,
  },
  {
    id: '6',
    teacherId: '1',
    subjects: ['1'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 0,
    price: 0,
  },
  {
    id: '7',
    teacherId: '1',
    subjects: ['1'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 5,
    price: 1000,
  },
  {
    id: '8',
    teacherId: '1',
    subjects: ['1'],
    type: AbonementType.limited,
    limitTime: 30,
    limitLessons: 5,
    price: 0,
  },
];

export const sampleSubjects: ISubjectView[] = [
  {
    id: '1',
    teacherId: '1',
    name: 'Математика',
    description: 'Описание предмета Математика',
    rules: [],
  },
  {
    id: '2',
    teacherId: '1',
    name: 'Физика',
    description: 'Описание предмета Физика',
    rules: [],
  },
  {
    id: '3',
    teacherId: '1',
    name: 'Химия',
    description: 'Описание предмета Химия',
    rules: [],
  },
  {
    id: '4',
    teacherId: '1',
    name: textL,
    description: 'Описание предмета Химия',
    rules: [],
  },
];

export const dummyLessons: ILesson [] = [
  {
    id: '1',
    date: new Date(),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
  {
    id: '2',
    date: new Date('2023-04-27T15:00:00.000Z'),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
  {
    id: '3',
    date: new Date('2023-04-27T18:00:00.000Z'),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
  {
    id: '4',
    date: new Date('2023-04-27T12:00:00.000Z'),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
  {
    id: '5',
    date: new Date('2023-04-25T20:00:00.000Z'),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
  {
    id: '6',
    date: new Date('2023-04-28T21:00:00.000Z'),
    durationMin: 60,
    accepted: [],
    declained: [],
    status: LessonStatus.scheduled,
    subject: dummySubjects[0],
    teacherId: '1568',
    participants: [],
  },
];

export const dummieUsers: IUser[] = [
  {
    id: 'test2 Ipsuma',
    avatar: '',
    name: 'test2 Ipsuma',
  },
  {
    id: 'test2 Lipsu',
    avatar: '',
    name: 'test2 Lipsu',
  },
  {
    id: 'test1 Swity',
    avatar: '',
    name: 'test1 Swity',
  },
  {
    id: 'test1 Down',
    avatar: '',
    name: 'test1 Down',
  },
];

export const dummieExternalTeachers: ITeacher[] = [
  {
    id: '1568',
    name: "Ololosh",
    avatar: '',
    description: 'test man',
    abonementOffers: [],
    subjects: []
  },
  {
    id: '6852',
    name: "Subsubin",
    avatar: '',
    description: 'test man',
    abonementOffers: [],
    subjects: []
  },
]

export const dummieExternalLessons: ILesson[] = [
  {
    id: '0001',
    durationMin: 50,
    date: new Date(),
    status: LessonStatus.inProcess,
    subject: dummySubjects[0],
    teacherId: 'test-teacher-id',
    accepted: ['test2 Ipsuma', 'test2 Lipsu'],
    declained: ['test1 Down'],
    participants: dummieUsers,
  },
  {
    id: '0002',
    durationMin: 120,
    date: new Date(Date.now() + oneDay + oneHour),
    status: LessonStatus.scheduled,
    subject: dummySubjects[1],
    teacherId: 'test-teacher-id',
    accepted: ['test2 Ipsuma'],
    declained: ['test1 Down'],
    participants: dummieUsers,
  },
  {
    id: '0003',
    durationMin: 14,
    date: new Date(Date.now() + oneDay*2 + oneHour*2),
    status: LessonStatus.scheduled,
    subject: dummySubjects[2],
    teacherId: 'test-teacher-id',
    accepted: ['test2 Lipsu'],
    declained: ['test2 Ipsuma'],
    participants: dummieUsers,
  },
  {
    id: '0004',
    durationMin: 120,
    date: new Date(Date.now() + oneDay*3 + oneHour*3),
    status: LessonStatus.done,
    subject: dummySubjects[3],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity'],
    declained: ['test2 Ipsuma'],
    participants: dummieUsers,
  },
  {
    id: '0005',
    durationMin: 120,
    date: new Date(Date.now() + oneDay*4 - oneHour*4),
    status: LessonStatus.finished,
    subject: dummySubjects[4],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity'],
    declained: ['test2 Ipsuma'],
    participants: dummieUsers,
  },
  {
    id: '0006',
    durationMin: 120,
    date: new Date(Date.now() + oneDay*5 + oneHour*5),
    status: LessonStatus.canceled,
    subject: dummySubjects[5],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers,
  },
  {
    id: '0007',
    durationMin: 120,
    date: new Date(Date.now() + oneDay*6 + oneHour*6),
    status: LessonStatus.commingSoon,
    subject: dummySubjects[6],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers, 
  },
  {
    id: '0008',
    durationMin: 120,
    date: new Date(Date.now() - oneDay - oneHour),
    status: LessonStatus.scheduled,
    subject: dummySubjects[7],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers,
  },
  {
    id: '0009',
    durationMin: 120,
    date: new Date(Date.now() - oneDay*2 - oneHour*2),
    status: LessonStatus.scheduled,
    subject: dummySubjects[8],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers,
  },
  {
    id: '0010',
    durationMin: 120,
    date: new Date(Date.now() - oneDay*3 - oneHour*3),
    status: LessonStatus.scheduled,
    subject: dummySubjects[9],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers,
  },
  {
    id: '0011',
    durationMin: 120,
    date: new Date(Date.now() - oneDay*4 - oneHour*4),
    status: LessonStatus.scheduled,
    subject: dummySubjects[10],
    teacherId: 'test-teacher-id',
    accepted: ['test1 Swity', 'test2 Ipsuma'],
    declained: ['test2 Lipsu'],
    participants: dummieUsers,
  }
]

export const dummyAbonementConsumables:IAbonementConsumable[] = [
  {
    id:'101',
    limitLessons: 0,
    limitTime: 0,
    price: 0,
    type: AbonementType.limited,
    subjects:[],
    dateStart: new Date(Date.now() + oneDay*6 + oneHour*6),
    lessonsAttended: [],
    studentId: '',
  },
  {
    id:'202',
    limitLessons: 2,
    limitTime: 22,
    price: 222,
    type: AbonementType.limited,
    subjects:['2'],
    dateStart: new Date(Date.now() + oneDay*5 + oneHour*5),
    lessonsAttended: [],
    studentId: '',
  },
  {
    id:'303',
    limitLessons: 3,
    limitTime: 30,
    price: 333,
    type: AbonementType.limited,
    subjects:['1', '2', '3', '4', '5',  '6', '7', '8', '9', '10'],
    dateStart: new Date(Date.now() + oneDay*4 + oneHour*4),
    lessonsAttended: [],
    studentId: '',
   },
  {
    id:'404',
    limitLessons: 0,
    limitTime: 0,
    price: 0,
    type: AbonementType.unlimited,
    subjects:[],
    dateStart: new Date(Date.now() + oneDay*3 + oneHour*3),
    lessonsAttended: [],
    studentId: '',
  },
  {
    id:'505',
    limitLessons: 2,
    limitTime: 22,
    price: 222,
    type: AbonementType.unlimited,
    subjects:['2'],
    dateStart: new Date(Date.now() + oneDay*2 + oneHour*2),
    lessonsAttended: [],
    studentId: '',
  },
  {
    id:'606',
    limitLessons: 3,
    limitTime: 30,
    price: 333,
    type: AbonementType.unlimited,
    subjects:['1', '2', '3', '4', '5',  '6', '7', '8', '9', '10'],
    dateStart: new Date(Date.now() + oneDay + oneHour),
    lessonsAttended: [],
    studentId: '',
  },
]

export const dummieSearchSelectOptions: IOption[]= [
  {
    id: '1',
    title: 'Option 1',
  },
  {
    id: '2',
    title: 'Option 2',
  },
  {
    id: '3',
    title: 'Option 3',
  }
];
